### ISSUE TITLE
Array in Array in Request answer

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/project_TBD#12]
Hi!

When requesting `http://40.127.101.155/api/twitter?request_type=popular` you deliver a array in an array see picture: 
![screenshot 2018-10-08 at 13 00 07](https://user-images.githubusercontent.com/6302670/46605803-02f4cd80-cafb-11e8-809e-1a67a3c05107.png)

This forces the _front-end Team_ to write `console.log(responseJson[key][0].platform)` instead of `console.log(responseJson[key].platform)`.

Please resolve,
Love love ❤️ from the Front-End

**Comment by Heenkeeee** [comment]
Fixed!
